# Generated by Django 6.0.6 on 2026-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
