# Generated by Django 6.0.6 on 2026-06-11 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_create_conversation_and_message_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
