# Generated by Django 6.0.6 on 2026-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_calling_and_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text="Image attachment — used when message_type is 'IMAGE'", null=True, upload_to='message_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File')], default='TEXT', help_text='Determines how the frontend renders this message', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, help_text="Generic file attachment — used when message_type is 'FILE'", null=True, upload_to='message_files/'),
        ),
    ]
