# Generated by Django 6.0.6 on 2026-06-11 21:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='slots_available',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='slots_filled',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_image',
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, help_text='Tournament banner image', null=True, upload_to='tournament_images/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='joined_slots',
            field=models.IntegerField(default=0, help_text='Number of slots already filled'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('SQUAD', 'Squad')], default='SOLO', help_text='Tournament match type: Solo, Duo, or Squad', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='room_id',
            field=models.CharField(blank=True, help_text='Tournament room ID – revealed after payment approval', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='room_password',
            field=models.CharField(blank=True, help_text='Tournament room password – revealed after payment approval', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_slots',
            field=models.IntegerField(default=16, help_text='Total available slots', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_name',
            field=models.CharField(choices=[('FREE_FIRE', 'Free Fire'), ('PUBG', 'PUBG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, help_text='Optional team name for Duo/Squad tournaments', max_length=100, null=True)),
                ('player_game_ids', models.JSONField(blank=True, help_text='JSON mapping of player IGNs and Game UIDs', null=True)),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket')], max_length=20)),
                ('sender_number', models.CharField(help_text="User's bKash/Nagad/Rocket number used for payment", max_length=15)),
                ('transaction_id', models.CharField(help_text='Transaction ID (TxID) from the payment', max_length=100)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
