# Generated by Django 6.0.6 on 2026-06-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_slots_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', 'bKash'), ('ROCKET', 'Rocket')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='sender_number',
            field=models.CharField(help_text="User's bKash/Rocket number used for payment", max_length=15),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='transaction_id',
            field=models.CharField(help_text='Transaction ID (TxID) from the payment – must be unique', max_length=100, unique=True),
        ),
    ]
