# Generated by Django 6.0.6 on 2026-06-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
