# Generated by Django 6.0.6 on 2026-06-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='title',
        ),
    ]
